const mapNewModelEtablishment = oldModel => {
  return {
    siret: oldModel.siret,
    siren: oldModel.siren,
    numero_tva_intracommunautaire: oldModel.numero_tva_intracommunautaire,
    naf_code: oldModel.naf,
    naf_libelle: oldModel.libelle_naf,
    code_effectif_entreprise: oldModel.code_effectif_entreprise,
    forme_juridique_code: oldModel.forme_juridique_code,
    forme_juridique: oldModel.forme_juridique,
    raison_sociale: oldModel.raison_sociale,
    nom_commercial: oldModel.nom_commercial,
    capital_social: oldModel.capital_social,
    date_creation: oldModel.date_creation,
    siret_siege_social: oldModel.siret_siege_social,
    siege_social: oldModel.siege_social === "" ? false : oldModel.siege_social,
    adresse: oldModel.adresse,
    complement_adresse: oldModel.complement_adresse || "",
    numero_voie: oldModel.numero_voie || "",
    type_voie: oldModel.type_voie || "",
    nom_voie: oldModel.nom_voie,
    code_postal: oldModel.code_postal,
    localite: oldModel.localite,
    code_insee_localite: oldModel.code_insee_localite,
    num_academie: oldModel.numAcademie || -1,
    nom: oldModel.nom,
    prenom: oldModel.prenom,
    ds_id_dossier: oldModel.ds_idDossier,
    ds_questions_siren: oldModel.ds_questions_siren,
    ds_questions_nom: oldModel.ds_questions_nom,
    ds_questions_email: oldModel.ds_questions_email,
    ds_questions_uai: oldModel.ds_questions_uai,
    ds_questions_has_agrement_cfa: oldModel.ds_questions_hasAgrementCFA,
    ds_questions_has_certificaton_2015: oldModel.ds_questions_hasCertificaton2015,
    ds_questions_has_ask_for_certificaton: oldModel.ds_questions_hasAskForCertificaton,
    ds_questions_ask_for_certificaton_date: oldModel.ds_questions_askForCertificatonDate,
    ds_questions_declaration_code: oldModel.ds_questions_declarationCode,
    ds_questions_has_2020_training: oldModel.ds_questions_has2020Training,
    uai: oldModel.uai,
    uais_formations: oldModel.uaisFormation,
    info_depp: oldModel.info_DEPP,
    info_dgefp: oldModel.info_DGEFP,
    info_datagouv_ofs: oldModel.info_datagouv_ofs,
    info_datadock: oldModel.info_dataDock,
    computed_type: oldModel.computed_isCfaOrOfa,
    computed_declare_prefecture: oldModel.computed_declare_prefecture,
    computed_conventionne: oldModel.computed_organisme_conventionne,
    computed_info_datadock: oldModel.computed_info_dataDock,
    computed_rncp_habilite: "",
    published: oldModel.published,
    created_at: oldModel.createdAt || Date.now(),
    last_update_at: oldModel.lastUpdateAt || Date.now(),
  };
};

module.exports = mapNewModelEtablishment;
